# Generated by Django 5.0.7 on 2024-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True,
                                    default='profile/default-profile.jpeg',
                                    upload_to='profile/'),
        ),
    ]
