version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hfn-frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    container_name: hfn-proxy

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: hfn-backend
    volumes:
      - ./backend:/app/backend
